Models/ErrorViewModel.cs
namespace CIS174_TestCoreApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace CIS174_TestCoreApp.Models
{
    public class Student
    {
        [Required]
        public string firstName { get; set; } = String.Empty;
        [Required]
        public string lastName { get; set; } = String.Empty;
        [Required]
        public string grade { get; set; } = String.Empty;
    }
}

Controllers/AssignmentController.cs
using CIS174_TestCoreApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace CIS174_TestCoreApp.Controllers
{
    public class AssignmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [Route("Assignment/List/{id?}")] //Routing pattern that connects to this IActionResult
        [HttpPost]
        public IActionResult List()
        {
            //ViewBag.Access = access;
            List<Student> studentList = new List<Student>();

            Student student = new Student();
            Student beth = new Student();
            Student gabriela = new Student();
            student.firstName = "Gabe";
            student.lastName = "Clark";
            student.grade = "A";
            studentList.Add(student);
            
            beth.firstName = "Bethany";
            beth.lastName = "Michaels";
            beth.grade = "B";
            studentList.Add(beth);

            gabriela.firstName = "Gabriela";
            gabriela.lastName = "Clark";
            gabriela.grade = "A+";
            studentList.Add(gabriela);

            studentList.ToString();
            //Creates three students and adds them to a List
            /*if (access <= 2)
            {
                studentList = null;
            }
            else if((access > 2) && (access < 8))
            {
                studentList = studentList.Select(p => p.firstName).ToList();
            }*/
            return View(studentList);
        }
    }
}

Controllers/HomeController.cs
using CIS174_TestCoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CIS174_TestCoreApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/StudentList.cshtml
@model List<Student>
@{
    ViewBag.Title = "Students List";
}
<h1>Students:</h1>
@if (ViewBag.Id <= 2)
{
    /*Will not show any info if Id is 2 or less*/
    <p>"You do not have a sufficient access level to view this data."</p>
}
else if ((ViewBag.Id > 2) && (ViewBag.Id < 8))
{
    /*Shows all first and last names in list if Id is above 2 but less than 8*/
    foreach (var student in @Model)
    {
        <tr>
            <td>@student.firstName</td>
            <td>@student.lastName</td>
        </tr>
    }
}
else if (ViewBag.Id >= 8)
{
    <p>Hello Admin</p>
    /*Shows all student info in list if Id is 8 or above*/
    foreach (var student in @Model)
    {
        <tr>
            <td>@student.firstName</td>
            <td>@student.lastName</td>
            <td>@student.grade</td>
        </tr>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CIS174_TestCoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CIS174_TestCoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CIS174_TestCoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">Contact</a>
                        </li>
                        <li role="presentation" class="dropdown">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Assignments</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Assignment" asp-action="List">Assignment 6.1</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CIS174_TestCoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>